### PR TITLE
Update build-to-do-list-aepp-1.md

### PR DESCRIPTION
**Pull request by Muchstix**
ak_2FbNgxusNhjy2a3WybXuokojSphFLiYnooo2NdQ6iWJHGkapaM

### CODE REVIEW

**Comment by Muchstix** [comment]
Am trying the rest out. Let me get back to you

**Comment by Muchstix** [comment]
getting an error while compiling ToDoManager.aes details in attachment.
Also making changes to prerequsites links

**Comment by thepiwo** [comment]
closing as there is no more progress, feel free to reopen

**Pull request closed without merging**
