### PR TITLE
Tutorial Updated by @emmanuelJet

### PR DESCRIPTION
**Pull request by emmanuelJet**
# TUTORIAL Update

Below are tutorials updated by @emmanuelJet.

- How to Get Testnet Funds
- How to Get Started With Unit Testing Using aeproject

I also changed the Tutorial title from How to Get Started With Unit Testing Using forgae to How to Get Started With Unit Testing Using aeproject in the Readme file. AE Address: ak_rLoCtHE3NK9dKyCNonJFYWkEEfeAsDUWa887GsCKqV1rhSuT6

### CODE REVIEW

**Comment by Jkat** [comment]
Your updates for the unit testing tutorial don't actually involve teaching people how to do any unit testing, it's missing the point of the tutorial.

**Comment by Jkat** [comment]
The testnet funds tutorial is still working pretty flawlessly as is, and you added a lot of whitespace. You did delete the output texts and replaced them with 2 screenshots but now we have to rely on a 3rd party hosting provider and if there are problems with the provider, the tutorial will be broken/need updating. So I'm not sure this change is going to improve things.

**Comment by emmanuelJet** [comment]
> Your updates for the unit testing tutorial don't actually involve teaching people how to do any unit testing, it's missing the point of the tutorial.

If it's not kindly elaborate more

**Comment by emmanuelJet** [comment]
> The testnet funds tutorial is still working pretty flawlessly as is, and you added a lot of whitespace. You did delete the output texts and replaced them with 2 screenshots but now we have to rely on a 3rd party hosting provider and if there are problems with the provider, the tutorial will be broken/need updating. So I'm not sure this change is going to improve things.

What if the images was changed to base 64 type like it was on the tutorial earlier

**Comment by emmanuelJet** [comment]
By the way @Jkat, 

> you added a lot of whitespace 

This is to follow the guide on how to write a readme. Check out [https://www.makeareadme.com/#markdown-input-editable](https://www.makeareadme.com/#markdown-input-editable) or [https://help.github.com/en/github/writing-on-github/about-writing-and-formatting-on-github](https://help.github.com/en/github/writing-on-github/about-writing-and-formatting-on-github)

**Comment by emmanuelJet** [comment]
> Your updates for the unit testing tutorial don't actually involve teaching people how to do any unit testing, it's missing the point of the tutorial.

But you know there is a Test Code section on the PR right?

**Comment by Jkat** [comment]
> > Your updates for the unit testing tutorial don't actually involve teaching people how to do any unit testing, it's missing the point of the tutorial.
> 
> If it's not kindly elaborate more

Unit testing is mainly about testing functions to make sure they behave as intended. `console.log` is not unit testing.

> > The testnet funds tutorial is still working pretty flawlessly as is, and you added a lot of whitespace. You did delete the output texts and replaced them with 2 screenshots but now we have to rely on a 3rd party hosting provider and if there are problems with the provider, the tutorial will be broken/need updating. So I'm not sure this change is going to improve things.
> 
> What if the images was changed to base 64 type like it was on the tutorial earlier

Sure, you can try this. I still believe it makes the tutorial harder to maintain in the long run.

> By the way @Jkat,
> 
> > you added a lot of whitespace
> 
> This is to follow the guide on how to write a readme. Check out https://www.makeareadme.com/#markdown-input-editable or https://help.github.com/en/github/writing-on-github/about-writing-and-formatting-on-github

If you view your markdown file, the whitespace added didn't have any effect. You also incorrectly added bash syntax highlighting at places with no bash code, but that's not a big deal.

> > Your updates for the unit testing tutorial don't actually involve teaching people how to do any unit testing, it's missing the point of the tutorial.
> 
> But you know there is a Test Code section on the PR right?

In the current version of this tutorial, the "Test Code" section talks about `deploy.js` which isn't where you test code. `deploy.js` is where you modify parameters for your deployment. The point of this tutorial is to teach people how to get started with writing and testing their smart contract functions.

**Comment by thepiwo** [comment]
@Jkat did you already check the updated tutorial? It looks okay to me

**Comment by thepiwo** [comment]
Some of the changes were overlapping with work @Jkat did, but I propose we resolve the conflicts here and merge this one as well.

**Comment by Jkat** [comment]
Yes the updated aeproject shape vue tutorial looks good to me too. The rest hasn't been addressed though, and as Piwo mentioned there have been other commits since, so I think this PR should either be rebased or an easier/cleaner solution may be to close and open a new PR with just the aeproject shape vue tutorial which can be merged quickly.

**Pull request closed without merging**
