### PR TITLE
Update account-creation-in-ae-cli.md

### PR DESCRIPTION
**Pull request by Muchstix**
This is my wallet address:         ak_25TktXHGr5oQuMjr4bx9mAPf3XrSzJAtMq29e7jTPKNwWLE3Wf

### CODE REVIEW

**Comment by Muchstix** [comment]
I heard of a 150$ bounty on a succesfull merge

**Comment by thepiwo** [comment]
The additions of how to install nodejs seem out of scope for this tutorial, as they may be different on each machine. Also markdown style adjustments don't seem necessary at this point in time.

**Comment by Muchstix** [comment]
Would it help to include installation instructions for Mac and windows?

**Comment by thepiwo** [comment]
@Muchstix I don't think this is neccessary, once nodejs is installed the workflow is the same on any platform

**Comment by Muchstix** [comment]
Node installation on windows is just fine. But there's an issue when it
comes to installing git. Aecli is not yot available in the npm repository.
So, in windows, I suggest steps be written for the installation of a Linux
distribution from the windows store. This would involve updating to the
latest windows 10 version and then enabling windows subsystem for Linux. A
Linux distro can be chosen, git and node installed. Then Aecli.

**Comment by thepiwo** [comment]
My opinion is to leave out windows instructions, as there may come lots more issues as official support is "experimental"

**Comment by Muchstix** [comment]
Yo the boss

On Oct 24, 2019 11:22 AM, "Philipp Piwo" <notifications@github.com> wrote:

My opinion is to leave out windows instructions, as there may come lots
more issues as official support is "experimental"

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/aeternity/tutorials/pull/57?email_source=notifications&email_token=ALHDPNJ56RH3YI4WUTTW42TQQFLNLA5CNFSM4JD7WP7KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECEFFMY#issuecomment-545804979>,
or unsubscribe

**Pull request closed without merging**
