### PR TITLE
Update Tutorials

### PR DESCRIPTION
**Pull request by GoodnessEzeokafor**
AE address : ak_2Hjzq1jBw2cYmQjqcfNRU29JFHQMwo5iBqxKRe2fM3PWPiMUti
I think every developer using window 8.1 and below should be aware they need to have Visual Studio Code 2017 installed on their os
I had an issue when when installing forgae, but after installing visual studio 2017 it worked
I also went through the to-do-list.aepps tutorial and found out that some of the syntax were deprecated so i changed it

### CODE REVIEW

**Comment by thepiwo** [comment]
@alekseytsekov or @Pegahbit can you review?

**Comment by GoodnessEzeokafor** [comment]
Wasn't my changes on Updated the Tutorial: build-to-do-list-aepp-1.md approved???

**Comment by GoodnessEzeokafor** [comment]
Mr Erik would like to know

**Comment by GoodnessEzeokafor** [comment]
I can see on the documentation that it was

**Pull request merged**
