### PR TITLE
Tutorial Updated by @emmanuelJet

### PR DESCRIPTION
**Pull request by emmanuelJet**
# TUTORIAL Update

I updated the `forgae-shape-vue-command.md` tutorial by changing all forgae command to aeproject command. 

I also changed the Tutorial title from `Forgae has made it simple to build Æpps with the front-end framework` to `AEproject has made it simple to build Æpps with the front-end framework` and also updated the file name to `aeproject-shape-vue-command.md` in the Readme file.

### CODE REVIEW

**Comment by Jkat** [comment]
I'm testing the tutorial right now and am getting several errors:

```
~/vue-shape$ aeproject deploy
Error: Error: Http request for http://localhost:3080/aci failed with status code 400. Status: Bad Request. 
Error data: [{"message":"Invalid type\n  (int, todo)  (at line 73, column 33)\nThe syntax of tuple types changed in Sophia version 4.0. Did you mean\n  (int * todo)\n","pos":{"col":33,"line":73},"type":"type_error"},{"context":"when checking the record projection at line 75, column 59\n  state.map_user_todos : map(address, map(int, todo))\nagainst the expected type\n  map(address, map(int, todo))\n","message":"Cannot unify todo\n         and todo\n","pos":{"col":59,"line":75},"type":"type_error"}]
```

Contract code doesn't compile either.

**Comment by emmanuelJet** [comment]
That's because there is a problem with the smart contract is the lima
release. Check out
https://github.com/aeternity/aepp-aeproject-shape-vue/blob/master/aepp/src/contractDetails.js
for the contract changes.

**Comment by Jkat** [comment]
So we need to wait for aeproject to make an update first? Are you able to create an issue in their repo so that the aeproject team is aware that this is broken?

**Comment by Muchstix** [comment]
We are the team?? 😁

**Comment by thepiwo** [comment]
closing as there is no more progress, feel free to reopen

**Pull request closed without merging**
